name: Deploy Paper

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: impact-scholars/isp-actions-config/.github/workflows/deploy-paper.yml@main
    with:
      base_url: /${{ github.event.repository.name }}
